# Generated by Django 2.2.4 on 2019-08-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fretboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=3)),
                ('string1', models.CharField(max_length=3)),
                ('string2', models.CharField(max_length=3)),
                ('string3', models.CharField(max_length=3)),
                ('string4', models.CharField(max_length=3)),
                ('string5', models.CharField(max_length=3)),
                ('string6', models.CharField(max_length=3)),
            ],
        ),
    ]
